const events = [
  {
    eventId: "1",
    eventName: "Summer Music Festival",
    date: "2024-08-15",
    description: "A vibrant festival celebrating the best of summer tunes.",
    location: "Central Park, New York",
  },
  {
    eventId: "2",
    eventName: "Jazz Nights",
    date: "2024-08-20",
    description: "An evening of smooth jazz performances by top artists.",
    location: "Blue Note, New York",
  },
  {
    eventId: "3",
    eventName: "Rock Concert",
    date: "2024-08-25",
    description: "High-energy rock concert featuring famous bands.",
    location: "Madison Square Garden, New York",
  },
  {
    eventId: "4",
    eventName: "Electronic Dance Party",
    date: "2024-09-01",
    description: "A night of electronic dance music with renowned DJs.",
    location: "Electric Zoo, New York",
  },
  {
    eventId: "5",
    eventName: "Classical Music Evening",
    date: "2024-09-10",
    description: "An elegant evening with performances by classical musicians.",
    location: "Carnegie Hall, New York",
  },
  {
    eventId: "6",
    eventName: "Hip Hop Showcase",
    date: "2024-09-15",
    description: "A showcase of the best hip hop talent.",
    location: "Apollo Theater, New York",
  },
  {
    eventId: "7",
    eventName: "Country Music Fest",
    date: "2024-09-20",
    description: "A festival celebrating the best of country music.",
    location: "Nashville Fairgrounds, Nashville",
  },
  {
    eventId: "8",
    eventName: "Indie Music Gathering",
    date: "2024-09-25",
    description: "An event featuring indie bands and artists.",
    location: "The Roxy, Los Angeles",
  },
  {
    eventId: "9",
    eventName: "Pop Extravaganza",
    date: "2024-10-01",
    description: "A concert showcasing popular pop artists.",
    location: "Staples Center, Los Angeles",
  },
  {
    eventId: "10",
    eventName: "Blues Festival",
    date: "2024-10-05",
    description: "A festival dedicated to the best blues music.",
    location: "House of Blues, Chicago",
  },
  {
    eventId: "11",
    eventName: "Reggae Jam",
    date: "2024-10-10",
    description: "A night of reggae music and dance.",
    location: "Reggae Rise Up, Miami",
  },
  {
    eventId: "12",
    eventName: "Folk Music Night",
    date: "2024-10-15",
    description: "An evening dedicated to folk music performances.",
    location: "Folk Alliance, Kansas City",
  },
  {
    eventId: "13",
    eventName: "Latin Music Fiesta",
    date: "2024-10-20",
    description: "A fiesta with performances by top Latin music artists.",
    location: "Fiesta Latina, Miami",
  },
  {
    eventId: "14",
    eventName: "Soul Music Celebration",
    date: "2024-10-25",
    description: "A celebration of soul music with live performances.",
    location: "Stax Museum, Memphis",
  },
];

module.exports = { events };
