const events = [
  {
    eventId: "1",
    eventName: "Summer Music Festival",
    date: "2024-08-15",
    description: "A vibrant festival celebrating the best of summer tunes.",
    location: "Central Park, New York",
  },
  {
    eventId: "2",
    eventName: "Jazz Nights",
    date: "2024-08-20",
    description: "An evening of smooth jazz performances by top artists.",
    location: "Blue Note, New York",
  },
  {
    eventId: "3",
    eventName: "Rock Concert",
    date: "2024-08-25",
    description: "High-energy rock concert featuring famous bands.",
    location: "Madison Square Garden, New York",
  },
  {
    eventId: "4",
    eventName: "Electronic Dance Party",
    date: "2024-09-01",
    description: "A night of electronic dance music with renowned DJs.",
    location: "Electric Zoo, New York",
  },
  {
    eventId: "5",
    eventName: "Classical Music Evening",
    date: "2024-09-10",
    description: "An elegant evening with performances by classical musicians.",
    location: "Carnegie Hall, New York",
  },
  {
    eventId: "6",
    eventName: "Hip Hop Showcase",
    date: "2024-09-15",
    description: "A showcase of the best hip hop talent.",
    location: "Apollo Theater, New York",
  },
  {
    eventId: "7",
    eventName: "Country Music Fest",
    date: "2024-09-20",
    description: "A festival celebrating the best of country music.",
    location: "Nashville Fairgrounds, Nashville",
  },
  {
    eventId: "8",
    eventName: "Indie Music Gathering",
    date: "2024-09-25",
    description: "An event featuring indie bands and artists.",
    location: "The Roxy, Los Angeles",
  },
  {
    eventId: "9",
    eventName: "Pop Extravaganza",
    date: "2024-10-01",
    description: "A concert showcasing popular pop artists.",
    location: "Staples Center, Los Angeles",
  },
  {
    eventId: "10",
    eventName: "Blues Festival",
    date: "2024-10-05",
    description: "A festival dedicated to the best blues music.",
    location: "House of Blues, Chicago",
  },
  {
    eventId: "11",
    eventName: "Reggae Jam",
    date: "2024-10-10",
    description: "A night of reggae music and dance.",
    location: "Reggae Rise Up, Miami",
  },
  {
    eventId: "12",
    eventName: "Folk Music Night",
    date: "2024-10-15",
    description: "An evening dedicated to folk music performances.",
    location: "Folk Alliance, Kansas City",
  },
  {
    eventId: "13",
    eventName: "Latin Music Fiesta",
    date: "2024-10-20",
    description: "A fiesta with performances by top Latin music artists.",
    location: "Fiesta Latina, Miami",
  },
  {
    eventId: "14",
    eventName: "Soul Music Celebration",
    date: "2024-10-25",
    description: "A celebration of soul music with live performances.",
    location: "Stax Museum, Memphis",
  },
  {
    eventId: "15",
    eventName: "Opera Gala",
    date: "2024-10-30",
    description: "A gala featuring performances from renowned opera singers.",
    location: "Metropolitan Opera House, New York",
  },
  {
    eventId: "16",
    eventName: "K-Pop Concert",
    date: "2024-11-05",
    description: "A concert featuring the top K-Pop bands.",
    location: "Staples Center, Los Angeles",
  },
  {
    eventId: "17",
    eventName: "Metal Mania",
    date: "2024-11-10",
    description: "A festival showcasing the best metal bands.",
    location: "Whisky a Go Go, Los Angeles",
  },
  {
    eventId: "18",
    eventName: "Punk Rock Show",
    date: "2024-11-15",
    description: "A show with performances by top punk rock bands.",
    location: "CBGB, New York",
  },
  {
    eventId: "19",
    eventName: "Electronic Beats",
    date: "2024-11-20",
    description: "A night dedicated to electronic music.",
    location: "Tomorrowland, Atlanta",
  },
  {
    eventId: "20",
    eventName: "Holiday Music Spectacular",
    date: "2024-12-01",
    description: "A spectacular event celebrating holiday music.",
    location: "Radio City Music Hall, New York",
  },
  {
    eventId: "21",
    eventName: "New Year's Eve Bash",
    date: "2024-12-31",
    description: "A grand celebration to ring in the new year.",
    location: "Times Square, New York",
  },
  {
    eventId: "22",
    eventName: "Spring Music Carnival",
    date: "2025-03-15",
    description:
      "A carnival with a variety of music performances to welcome spring.",
    location: "Grant Park, Chicago",
  },
  {
    eventId: "23",
    eventName: "Acoustic Evening",
    date: "2025-03-20",
    description: "An evening of acoustic music performances.",
    location: "The Troubadour, Los Angeles",
  },
  {
    eventId: "24",
    eventName: "Reggae Roots Festival",
    date: "2025-03-25",
    description: "A festival celebrating the roots of reggae music.",
    location: "Reggae Rise Up, Miami",
  },
  {
    eventId: "25",
    eventName: "Blues and Brews",
    date: "2025-04-01",
    description: "A festival with blues music and craft beer.",
    location: "Millennium Park, Chicago",
  },
  {
    eventId: "26",
    eventName: "Alternative Music Fest",
    date: "2025-04-05",
    description: "A festival featuring top alternative music bands.",
    location: "Golden Gate Park, San Francisco",
  },
  {
    eventId: "27",
    eventName: "Hip Hop Block Party",
    date: "2025-04-10",
    description: "A block party with performances by hip hop artists.",
    location: "Venice Beach, Los Angeles",
  },
  {
    eventId: "28",
    eventName: "World Music Day",
    date: "2025-06-21",
    description: "A day celebrating music from around the world.",
    location: "Central Park, New York",
  },
  {
    eventId: "29",
    eventName: "Garage Band Showcase",
    date: "2025-06-30",
    description: "A showcase of the best garage bands.",
    location: "Echo Park, Los Angeles",
  },
  {
    eventId: "30",
    eventName: "Latin Beats",
    date: "2025-07-05",
    description: "A night of Latin music and dance.",
    location: "Fiesta Latina, Miami",
  },
];

module.exports = { events };
